### PR TITLE
Respect original file encoding of AssemblyInfo.cs

### PR DESCRIPTION
**Pull request by jbrejner**
Fix issue when writing the changed file back, then the original file's encoding was ignored, and java just used what i thought appropriate for the platform. The result was files that could not be read by Visual Studio (msbuild).
This fix, detects the encoding of the original file and writes the modifed file with same encoding.

### CODE REVIEW

**Comment by mdkf** [comment]
@jbrejner I included your fix in my PR here: https://github.com/jenkinsci/change-assembly-version-plugin/pull/9

**Comment by DuAell** [comment]
Any chance to have it merged ?

**Comment by slide** [comment]
@DuAell no, it can't be merged, it doesn't build.

**Comment by slide** [comment]
Yes, I can probably pull in just the BOMInputStream stuff, but not the other stuff.

**Comment by DuAell** [comment]
It's probably the same problem the one mentioned here : https://github.com/jenkinsci/change-assembly-version-plugin/pull/11

**Comment by mdkf** [comment]
@DuAell Use the patch I submitted here https://github.com/jenkinsci/change-assembly-version-plugin/pull/9

**Comment by jbrejner** [comment]
Appears to have been fixed already, so no need for this PR https://github.com/jenkinsci/change-assembly-version-plugin/pull/9

**Pull request closed without merging**
