### PR TITLE
use jenkins FilePath methods to achieve the same results

### PR DESCRIPTION
**Pull request by nilleb**
the code is now lighter. I have writter a unit test covering the scope of the original code.
I think that this code doesn't repeat itself and it fullfills the original aim.

furthermore, this new implementation solves a bug related to remote execution (i.e. on a windows slave)

### CODE REVIEW

**Comment by nilleb** [comment]
Let me explain a bit more why it is important for you to accept this pull request.

1) the code is now limited to the essential. Yet it does the same thing of the code I have deleted. The greatest difference with the older code is that I'm using native Jenkins types and methods. The oldest code repeated itself a few times.

2) The code I had submitted in a previous pull request (#4) contained a bug. When executing a job on a windows slave, the paths handled by this plugin weren't relative to the host, but absolute URIs identifying the file in the workspace exposed by the Jenkins server web application. I have changed the code in order to use a FileCallable. This change allows windows slaves to use the change-assembly-version plugin without errors.

3) This code is tested by a unit test.

4) The plugin, in its new version, has been deployed and used on a test server, delegating jobs to windows slaves.

Thanks for your attention,
Ivo

**Comment by lkobus** [comment]
Thanks Ivo I'm really out of time going to release this version today if you can edit the wiki later i would appreciate.

[] ' s

**Comment by nilleb** [comment]
Hello Leonardo,

I cant' see a new release of your plugin. Are you sure you've released it
on sunday?

I'm waiting for your release in order to edit the wiki.

My source:
https://wiki.jenkins-ci.org/display/JENKINS/Change+Assembly+Version

See you,
Ivo

Le Fri Jan 23 2015 at 17:07:11, Leonardo Kobus <notifications@github.com> a
écrit :

**Comment by lkobus** [comment]
Hi nileb i forgot just used release:prepare and not perform.
I checked one problem when releasing perform, he build and after that he test the application to deploy, but in my machine the test are failling.
This appear to be a problem with windows Injected test when read some issues about the problem.
Did you execute test via JUNIT runner in eclipse? If so can you try mvn test (it's where fails) I tried to use dispose and System.gc() in your test routine but didn't work, it's appear that Tear down throw IO Exception when try to release resources.

I'll try spend more time in the week for this, but i'm really out of time so...
thx.

**Comment by nilleb** [comment]
Probably your issue is related to the jenkins versions you've in your
pom.xml.

I've experienced the same problem, and after some googling I got a
successful build (including the InjectedTest).

Which version of Java are you using? On which OS?

(In my case it is Java 1.8 on Mac OS X)

**Comment by lkobus** [comment]
Windows 7 Enterprise 
Java 1.8
Strange, I gonna check de Jenkins version and try again.

**Comment by lkobus** [comment]
Great @nilleb  :D it's worked and released!
Sorry for the delay, I just changed the version of jenkins on the pom for the one before your commit, idk if this gonna make any problem but if yes, I gonna research this problem on my machine.
Thanks!

**Pull request merged**
